"""GitHub-side effects: fix PRs, flag comments, and the idempotent summary."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from git import Repo

from doc_sentinel.detection.models import CheckReport
from doc_sentinel.repair.models import RepairMode, RepairReport, SectionRepair

SUMMARY_MARKER = "<!-- doc-sentinel-summary -->"
FIX_BRANCH_PREFIX = "doc-sentinel/fix-"


class PullRequestLike(Protocol):
    def get_issue_comments(self) -> Any: ...

    def create_issue_comment(self, body: str) -> Any: ...


class RepoLike(Protocol):
    def create_pull(self, *, title: str, body: str, head: str, base: str) -> Any: ...


def section_link(repo_html_url: str, sha: str, repair: SectionRepair) -> str:
    section = repair.verified.suspect.section
    return f"{repo_html_url}/blob/{sha}/{section.file}#L{section.start_line}-L{section.end_line}"


def _repair_line(repair: SectionRepair, repo_html_url: str, sha: str) -> str:
    section = repair.verified.suspect.section
    changes = ", ".join(c.describe() for c in repair.verified.suspect.changes)
    link = section_link(repo_html_url, sha, repair)
    detail = ""
    verdict = repair.verified.verdict
    if verdict and verdict.issues:
        detail = f" — {verdict.issues[0].what_is_wrong}"
    return f"- [`{section.heading_display}`]({link}) ({changes}){detail}"


def build_summary_body(
    check: CheckReport,
    repair: RepairReport,
    repo_html_url: str,
    head_sha: str,
    fix_pr_url: str | None,
    usage_summary: str | None,
) -> str:
    fixed = repair.by_mode(RepairMode.AUTO_FIX)
    drafted = repair.by_mode(RepairMode.DRAFT_WITH_TODOS)
    flagged = repair.by_mode(RepairMode.FLAG_ONLY)
    verified_ok = len(check.accurate)

    headline_bits = [f"{verified_ok} section(s) verified accurate"]
    if fixed or drafted:
        target = f" (see [{fix_pr_url}]({fix_pr_url}))" if fix_pr_url else ""
        headline_bits.append(f"{len(fixed) + len(drafted)} auto-fixed{target}")
    if flagged:
        headline_bits.append(f"{len(flagged)} flagged for review")

    lines = [
        SUMMARY_MARKER,
        f"## 🩺 Doc Check Results: {', '.join(headline_bits)}",
        "",
        f"Analyzed {len(check.changes)} meaningful code change(s) against the docs index.",
    ]
    if fixed:
        lines += ["", "### ✅ Auto-fixed"]
        lines += [_repair_line(r, repo_html_url, head_sha) for r in fixed]
    if drafted:
        lines += ["", "### 📝 Draft fixes (TODO markers, please review)"]
        lines += [_repair_line(r, repo_html_url, head_sha) for r in drafted]
    if flagged:
        lines += ["", "### ⚠️ Flagged for human review"]
        lines += [_repair_line(r, repo_html_url, head_sha) for r in flagged]
    if not (fixed or drafted or flagged):
        lines += ["", "No documentation drift detected. 🎉"]
    if usage_summary:
        lines += ["", f"<sub>LLM usage: {usage_summary}</sub>"]
    return "\n".join(lines)


def upsert_summary_comment(pr: PullRequestLike, body: str) -> None:
    """Update the existing doc-sentinel comment if present; never post duplicates."""
    for comment in pr.get_issue_comments():
        if SUMMARY_MARKER in (comment.body or ""):
            comment.edit(body)
            return
    pr.create_issue_comment(body)


def build_fix_pr_body(repair: RepairReport, pr_number: int) -> str:
    lines = [
        f"Automated documentation fixes for changes introduced in #{pr_number}.",
        "",
        "| Section | Change in code | Correction |",
        "|---|---|---|",
    ]
    for r in repair.repairs:
        if r.mode == RepairMode.FLAG_ONLY or r.correction is None:
            continue
        section = r.verified.suspect.section
        changes = "; ".join(c.describe() for c in r.verified.suspect.changes)
        if r.correction.edits:
            fix = "; ".join(
                f"`{e.old_text[:60]}` → `{e.new_text[:60]}`" for e in r.correction.edits[:3]
            )
        else:
            fix = "section rewritten"
        fix = fix.replace("|", "\\|")
        changes = changes.replace("|", "\\|")
        lines.append(f"| `{section.heading_display}` ({section.file}) | {changes} | {fix} |")
    lines += [
        "",
        "Generated by [doc-sentinel](https://github.com/marketplace). "
        "Sections marked with `TODO(doc-sentinel)` need human review before merge.",
    ]
    return "\n".join(lines)


def push_fix_branch(
    repo_path: Path,
    branch: str,
    files: dict[str, str],
    message: str,
    author_name: str = "doc-sentinel[bot]",
    author_email: str = "doc-sentinel@users.noreply.github.com",
) -> None:
    """Create/update the fix branch with the patched files and push it."""
    repo = Repo(repo_path)
    repo.git.checkout("-B", branch)
    for rel_path, content in files.items():
        (repo_path / rel_path).write_text(content, encoding="utf-8")
        repo.git.add(rel_path)
    repo.git.commit(
        "-m",
        message,
        author=f"{author_name} <{author_email}>",
    )
    repo.git.push("--force-with-lease", "--set-upstream", "origin", branch)


def open_fix_pr(
    gh_repo: RepoLike,
    branch: str,
    base_branch: str,
    pr_number: int,
    repair: RepairReport,
) -> Any:
    return gh_repo.create_pull(
        title=f"docs: fix stale documentation for #{pr_number}",
        body=build_fix_pr_body(repair, pr_number),
        head=branch,
        base=base_branch,
    )
